### PR TITLE
Privatized Priority List Nodes by Moving Them Into `struct nvme_iod`

### LINKED ISSUE #28: Ensure list usage is safe with blk-mq / request lifecycle
#### Implementation notes

Defensive patterns:

- Always list_del_init() when removing.

- Ensure the list head is initialized before use.

- Consider moving list node into struct nvme_iod (driver-private), which avoids conflicts with generic struct request fields.

- Decide ownership rules:

  - Refer to the request ownership model in the Linux block layer for a good reference.

#### Acceptance check

- Reset/unplug under load does not crash or leak.

### PR DESCRIPTION
**Pull request by Benjamin-Anderson-II**
Closes #28 

Previously nodes in the high/normal priority lists contained `queuelist` items found in `struct request`. This caused a potential security risk, since those structures are open to the rest of the kernel. This issue moves them into `struct nvme_iod` which is localized to a single I/O request. This is more semantically in-line with the purpose of these nodes and their containing struct while increasing their usage safety.

A guard was also placed inside the nvme's pci complete callback, `nvme_pci_complete_rq()` to make sure initialized qos_nodes got unlinked from the lists in the event of a cancel/timeout/reset.

### CODE REVIEW

File: drivers/nvme/host/pci.c [hunk 1]
```diff
@@ -1516,6 +1366,17 @@ static void nvme_pci_complete_rq(struct request *req)
...
+	/* Make sure the qos_node is unlinked in the event of a cancel/timeout/etc. */
+	struct nvme_iod *iod = blk_mq_rq_to_pdu(req);
+	/* 
+	 * AS OF RIGHT NOW: 
+	 *   QoS Nodes have only 1 element. Thus if it isn't empty, it isn't initialized.
+	 *   This is a protection in place for when the system boots.
+	 */
+    if(!list_empty(&iod->qos_node))
+		return;
+	list_del_init(&iod->qos_node);
```
Comment (BrandonPacewic) [inline drivers/nvme/host/pci.c]: Putting the cleanup here after `nvme_complete_rq(req);` introduces a use-after-free.

**Review by BrandonPacewic — CHANGES_REQUESTED** [review]
Should fix the merge conflicts from master. The merge looks non-trivial.

File: drivers/nvme/host/pci.c [hunk 2]
```diff
@@ -530,6 +535,14 @@ static int nvme_pci_init_request(struct blk_mq_tag_set *set,
 {
 	struct nvme_iod *iod = blk_mq_rq_to_pdu(req);
 
+#ifdef CONFIG_NVME_QOS
+	/*
+	 * Make sure the qos_node is initialized before adding it to the prio list.
+	 * Do this before bypass so that nvme_pci_complete_rq works everytime
+	 */
```
Comment (BrandonPacewic) [inline drivers/nvme/host/pci.c]: The comment is now stale. Was written as if its still in `nvme_queue_rq`. Now that it's in `nvme_pci_init_request`, there is no bypass to speak of.
