### PR TITLE
Route batch submission path through QoS schedule

### LINKED ISSUE #54: Integrate QoS classification into `nvme_queue_rqs()` batch submission path
#### Problem

`nvme_queue_rqs()` is the blk-mq batch submission path. When the block layer batches multiple requests, it calls `nvme_queue_rqs()` instead of `nvme_queue_rq()`. Currently, `nvme_queue_rqs()` submits all requests directly to the SQ via `nvme_submit_cmds()` with **no priority classification and no WRR arbitration**. This completely bypasses the QoS scheduler.

In practice this means the normal-priority bulk writes (which generate high batch volumes) flood the SQ unchecked, while high-priority reads that arrive via `nvme_queue_rq()` get enqueued into priority lists and must wait for `nvme_qos_kick()` to drain them.

**Benchmark evidence**: At qd=16 with a mixed 4K-read + 1M-write workload, QoS-enabled p99 is **10x worse** than baseline (+1012.7%) because the writes bypass the scheduler entirely.

#### Implementation notes

- When `qos_enabled`, `nvme_queue_rqs()` must classify each request (ioprio + namespace policy) and enqueue into `high_prio_list` / `normal_prio_list`.
- After enqueuing the batch, run the same bounded WRR dispatch loop used in `nvme_queue_rq()` to submit up to available SQ slots.
- When `qos_enabled == 0`, preserve the current direct-submit fast path unchanged.
- Consider the interaction with `nvme_commit_rqs()` and doorbell batching (#27).
- Must respect `NVME_QOS_MAX_BATCH` or equivalent dispatch bound to keep lock hold time bounded (#26).

#### Acceptance check

- Under mixed workload (RT reads + BE writes), the batch path respects priority classification.
- QoS-enabled p99 for high-priority reads at qd=16 and qd=32 is **equal to or better than** baseline, not worse.
- When QoS is disabled, no performance regression vs current behavior.
- No new lock ordering issues between `sq_lock` and blk-mq batch iteration.

### PR DESCRIPTION
**Pull request by BrandonPacewic**
Closes #54.

### TLDR

The batch submission path (where most I/O actually goes) was completely bypassing QoS - so the scheduler was basically a no-op. This patch fixes that, plus a deadlock in the locking. Benchmarks now show a regression because we're measuring real QoS overhead for the first time. The scheduler algorithm itself needs to get smarter (fast-path bypass, better token bucket, tunable batch limits) before we'll see the p99 improvement we're after.

### Summary

Previously `nvme_queue_rqs()` called `nvme_submit_cmds()` directly regardless of `qos_enabled`. Since blk-mq prefers the batch path over `nvme_queue_rq()`, most I/O never hit the QoS scheduler. Benchmark results with the old code showed QoS as "neutral" - but only because it wasn't being applied.

This patch makes QoS actually functional across all submission paths. The benchmark now correctly reflects the real cost of the scheduling logic.

  - Route `nvme_queue_rqs()` batch submission through QoS classification and WRR dispatch when `qos_enabled`, fixing the scheduler bypass that made QoS effectively inactive under normal blk-mq batching.
  - Fix IRQ deadlock on `sq_lock` by converting all acquisitions to `spin_lock_irqsave` (kick path runs in hard IRQ context).
  - Consolidate duplicate dispatch/classification logic into shared helpers (`nvme_qos_dispatch`, `nvme_qos_is_high_prio`, `nvme_sq_submit_cmd`)
  - Fix off-by-one in drain loop and add QoS state reset on queue reinit (this crashed my machine multiple times)
    - https://github.com/Enhanced-NVMe-QoS-Scheduler/nvme-qos-linux/blob/24825cf5f4a8aa68f9865c649cfebed511571db7/drivers/nvme/host/pci.c#L1237-L1238

### Benchamrks

With QoS now applied to all paths, the overhead of the current scheduler is visible (quick run, mixed 4K RT reads + 1MB BE writes):

```
branp:~/nvme-qos-linux$ sudo ./tools/nvme-qos-bench/nvme_qos_bench.py run --quick
[sudo] password for branp:
Using saved device: /dev/nvme0n1p7
nvme-qos-bench v0.0.1 | nvme0n1p7 | kernel 6.18.0-rc2-nvme-dev+ | QoS: available
---
baseline qd=16 : p50=   1.2ms p90=   1.6ms p99=   8.4ms p999=  15.8ms iops=   11.6K cpu=  2.8% [66.7s]
baseline qd=32 : p50=   2.1ms p90=   4.5ms p99=  11.6ms p999=  44.0ms iops=   11.5K cpu=  2.9% [66.7s]
qos w=9  qd=16 : p50=   1.4ms p90=   3.2ms p99=   9.6ms p999=  48.8ms iops=    7.8K cpu=  2.0% [67.6s]  +14.3%
qos w=9  qd=32 : p50=   2.5ms p90=   6.2ms p99=  19.7ms p999= 244.8ms iops=    6.9K cpu=  1.8% [66.8s]  +69.8%
---
summary: p99 +14.3% to +69.8% | iops -40.5% to -33.0% | cpu -37.4% to -30.7%

Results saved to: results/run_2026-02-05_23-30-09
Total runtime: 4m 27.7s
branp:~/nvme-qos-linux$ sudo ./tools/nvme-qos-bench/nvme_qos_bench.py run
Using saved device: /dev/nvme0n1p7
nvme-qos-bench v0.0.1 | nvme0n1p7 | kernel 6.18.0-rc2-nvme-dev+ | QoS: available
---
baseline qd=16 : p50=   1.3ms p90=   3.2ms p99=  37.8ms p999= 184.8ms iops=    6.1K cpu=  1.6% [326.7s]
baseline qd=32 : p50=   3.6ms p90=   7.5ms p99=  69.7ms p999= 641.3ms iops=    4.5K cpu=  1.2% [328.2s]
baseline qd=64 : p50=  14.4ms p90=  20.8ms p99= 470.6ms p999=   2.08s iops=    2.3K cpu=  0.7% [331.0s]
qos w=9  qd=16 : p50=   2.2ms p90=   4.2ms p99=  73.7ms p999= 490.7ms iops=    3.3K cpu=  0.9% [329.7s]  +94.7%
qos w=9  qd=32 : p50=   4.9ms p90=   8.7ms p99= 170.9ms p999=   1.43s iops=    2.7K cpu=  0.8% [329.3s]  +145.3%
qos w=9  qd=64 : p50=  11.3ms p90=  28.8ms p99= 478.0ms p999=   2.38s iops=    3.6K cpu=  0.9% [332.2s]  +1.6%
---
summary: p99 +1.6% to +145.3% | iops -46.9% to +57.2% | cpu -41.6% to +21.8%

Results saved to: results/run_2026-02-05_23-34-43
Total runtime: 32m 57.2s
```

vs how it used to be previous to this patch:

```
branp:~/nvme-qos-linux$ sudo ./tools/nvme-qos-bench/nvme_qos_bench.py run --quick
[sudo] password for branp:
Using saved device: /dev/nvme0n1p7
nvme-qos-bench v0.0.1 | nvme0n1p7 | kernel 6.18.0-rc2-nvme-dev+ | QoS: available
---
baseline qd=16 : p50=   987us p90=   1.6ms p99=   8.0ms p999=  13.3ms iops=   13.1K cpu=  3.2% [66.7s]
baseline qd=32 : p50=   2.1ms p90=   3.1ms p99=   9.6ms p999=  28.0ms iops=   13.2K cpu=  3.2% [66.7s]
qos w=9  qd=16 : p50=   893us p90=   1.4ms p99=   7.8ms p999=  12.8ms iops=   14.7K cpu=  3.5% [66.6s]  -3.3%
qos w=9  qd=32 : p50=   2.2ms p90=   3.6ms p99=  10.0ms p999=  33.1ms iops=   12.2K cpu=  3.0% [66.7s]  +4.8%
---
summary: p99 -3.3% to +4.8% | iops -7.2% to +12.2% | cpu -6.9% to +9.1%

Results saved to: results/run_2026-02-05_18-56-02
Total runtime: 4m 26.7s
branp:~/nvme-qos-linux$ sudo ./tools/nvme-qos-bench/nvme_qos_bench.py run
Using saved device: /dev/nvme0n1p7
nvme-qos-bench v0.0.1 | nvme0n1p7 | kernel 6.18.0-rc2-nvme-dev+ | QoS: available
---
baseline qd=16 : p50=   1.0ms p90=   2.2ms p99=   8.7ms p999=  41.8ms iops=   11.2K cpu=  2.7% [327.5s]
baseline qd=32 : p50=   5.2ms p90=   9.7ms p99= 152.8ms p999=   1.06s iops=    3.1K cpu=  0.9% [330.3s]
baseline qd=64 : p50=  16.1ms p90=  45.4ms p99= 720.6ms p999=   2.85s iops=    1.3K cpu=  0.5% [330.9s]
qos w=9  qd=16 : p50=   2.2ms p90=   4.4ms p99=  97.2ms p999= 683.3ms iops=    2.5K cpu=  0.8% [328.0s]  +1012.7%
qos w=9  qd=32 : p50=   5.2ms p90=   9.0ms p99= 179.7ms p999= 805.7ms iops=    2.8K cpu=  0.9% [331.1s]  +17.6%
qos w=9  qd=64 : p50=  15.0ms p90=  22.9ms p99= 500.8ms p999=   2.37s iops=    1.8K cpu=  0.6% [334.6s]  -30.5%
---
summary: p99 -30.5% to +1012.7% | iops -78.1% to +42.2% | cpu -71.5% to +34.2%

Results saved to: results/run_2026-02-05_19-01-31
Total runtime: 33m 2.4s
```

  ## Known issues / next steps

  This patch provides the correct structural foundation but the scheduler algorithm needs optimization before QoS delivers a net improvement:

  - **Enqueue-then-immediately-dequeue overhead**: Every request pays list_add + list_del even when there is no priority contention. A fast-path bypass when only one priority class is active would eliminate this for the common case.
  - **`NVME_QOS_MAX_BATCH=4` double-throttles the batch path**: blk-mq batches are already bounded. Capping dispatch at 4 forces larger batches to wait for completion kicks, directly causing IOPS loss. (#55)
  - **Token bucket semantics (#30)**: Credits reset to full when depleted rather than refilling at a rate. No time/completion-based pacing.
  - **Burst cap (#31)**: No limit on high-priority burst after idle.
  - **Low-depth bypass (#32)**: At low queue depths, scheduling overhead exceeds benefit. A bypass for uncontended scenarios would help

### CODE REVIEW

**Comment by phannawich** [comment]
If you are looking at the performance benchmark before this branch got merge.

What I have done is commenting out the batch path entirely to force I/O to come through the QoS.

File: drivers/nvme/host/pci.c [hunk 1]
```diff
@@ -1218,16 +1234,17 @@ static void nvme_qos_drain_all_queues(struct nvme_dev *dev)
 	unsigned int i;
 	int total = 0;
 
-	/* Skip admin queue (qid 0), drain I/O queues (1 to online_queues) */
-	for (i = 1; i <= dev->online_queues; i++) {
+	/* Skip admin queue (qid 0), drain I/O queues (1 to online_queues-1) */
+	for (i = 1; i < dev->online_queues; i++) {
```
Comment (phannawich) [inline drivers/nvme/host/pci.c]: Nice job catching this, otherwise, it will cause issue in booting the kernel.

**Comment by phannawich** [comment]
Waiting for Kconfig update

File: drivers/nvme/host/pci.c (hunk 1 above)
Comment (BrandonPacewic) [reply drivers/nvme/host/pci.c]: Yea this crashed my computer multiple times.
