### PR TITLE
Flush QoS lists safely

### LINKED ISSUE #49: Reset/timeout handling: flush QoS lists safely
On controller reset / queue reinit:

- Ensure any queued-but-not-submitted requests are requeued or failed consistently with existing NVMe behavior.

- Ensure lists are empty before freeing queue structures.

### LINKED ISSUE #71: Drain QoS lists before `nvme_cancel_tagset`
When `nvme_cancel_tagset` fires during `nvme_dev_disable()`, it calls `blk_mq_complete_request` for every in-flight request - including requests still linked into QoS priority lists. The completion path doesn't list_del them. The code currently relies on an undocumented ordering assumption that nothing touches the lists between cancel (line 3518) and `nvme_init_queue` reinitializing the list heads later. An explicit `nvme_qos_drain_all_queues()` call before cancel would make this safe by construction rather than by accident.

https://github.com/Enhanced-NVMe-QoS-Scheduler/nvme-qos-linux/blob/711b446a10178301da36a86f63f46ebb84d3cd6e/drivers/nvme/host/pci.c#L3517-L3520

### LINKED ISSUE #93: nvme_qos_purge_queue_locked does not consider nvme_iod
`nvme_qos_purge_queue_locked` consider `request queuelist` instead of `nvme_iod`

This issues is possible to be closed by #79, if not, we have to create a separate PR.

Consider two possibility:

1. Change `request` to `iod`
```
static void nvme_qos_purge_queue_locked(struct nvme_queue *nvmeq)
{
	struct nvme_iod *iod, *tmp;

	list_for_each_entry_safe(iod, tmp, &nvmeq->high_prio_list, qos_node)
		list_del_init(&iod->qos_node);

	list_for_each_entry_safe(iod, tmp, &nvmeq->normal_prio_list, qos_node)
		list_del_init(&iod->qos_node);
}
```

2. Add `iod` to purge_queue
```
static void nvme_qos_purge_queue_locked(struct nvme_queue *nvmeq)
 {
    struct request *req, *tmp;
    struct nvme_iod *iod, *tmp;
 
    list_for_each_entry_safe(req, tmp, &nvmeq->high_prio_list, queuelist)
	    list_del_init(&req->queuelist);
    list_for_each_entry_safe(iod, tmp, &nvmeq->high_prio_list, qos_node)
	    list_del_init(&iod->qos_node);
 
    list_for_each_entry_safe(req, tmp, &nvmeq->normal_prio_list, queuelist)
        list_del_init(&req->queuelist);
    list_for_each_entry_safe(iod, tmp, &nvmeq->normal_prio_list, qos_node)
	    list_del_init(&iod->qos_node);
 }
```

### PR DESCRIPTION
**Pull request by TSrirama2026**
- Adding nvme_qos_fail_queued_requests() to drain and fail requests that are both high and low priority
- Use list_splice_init() atomically claiming list contents under sq_lock, then release to avoid deadlock
- Ensure new requests can't be enqueued before the drain calling nvme_qos_fail_queued_requests() after calling NVMEQ_ENABLED
- Added drain loop in nvme_free_queue() to handle queues that were submitted but not brought online
- Call nvme_qos_fail_all_queued_requests() before nvme_dev_disable() as defense-in-depth. The drain in nvme_suspend_queue() covers any requests enqueued between the reset trigger and queue suspension

### CODE REVIEW

File: drivers/nvme/host/pci.c
Comment (phannawich) [inline drivers/nvme/host/pci.c]: This code is duplicate, I think you can make it clean up and free queue at the same time

**Review by phannawich — CHANGES_REQUESTED** [review]
I only look at some Kconfig for now, will look at the logic from this PR later

**Comment by phannawich** [comment]
I believe that this still need to be merged with the master branch.

File: drivers/nvme/host/pci.c [hunk 1]
```diff
@@ -1280,6 +1269,55 @@ static void nvme_qos_drain_all_queues(struct nvme_dev *dev)
...
+	list_splice_init(&nvmeq->normal_prio_list, &local);
+	spin_unlock_irqrestore(&nvmeq->sq_lock, flags);
+
+	while (!list_empty(&local)) {
+		req = list_first_entry(&local, struct request, queuelist);
+		list_del_init(&req->queuelist);
+		nvme_req(req)->status = NVME_SC_HOST_ABORTED_CMD;
+		nvme_req(req)->flags |= NVME_REQ_COMPLETE;
+		blk_mq_complete_request(req);
+	}
```
Comment (phannawich) [inline drivers/nvme/host/pci.c]: From my understanding, 
What you try to do is marking each request as aboard and send it back to blk_mq.
This could cause a race condition when you try to set a status.
For example, a thread might try to set a status as abort while another thread just finish sending a batch and reach QoS list to grab the same request. It will cause the hardware trying to complete a request that kernel think it is finish

Comment (phannawich) [reply drivers/nvme/host/pci.c]: Also, I think that Brandon mentioned there is no NVME_REQ_COMPLETE flag in the nvme.h

**Review by phannawich — CHANGES_REQUESTED** [review]

File: drivers/nvme/host/pci.c [hunk 2]
```diff
@@ -2302,6 +2202,14 @@ static void nvme_suspend_queue(struct nvme_dev *dev, unsigned int qid)
...
+
+	/* Fail queued but not submitted requests before
+	 * suspending to avoid stalling on a frozen queue
+	 */
+	nvme_qos_fail_queued_requests(nvmeq);
+#endif
+
 	nvmeq->dev->online_queues--;
 	if (!nvmeq->qid && nvmeq->dev->ctrl.admin_q)
 		nvme_quiesce_admin_queue(&nvmeq->dev->ctrl);
```
Comment (phannawich) [inline drivers/nvme/host/pci.c]: As you can see, the code below utilize quiesce, I believe that if you not call quiesce, the block layer will keep giving you a new list for you to clean.

**Review by phannawich — CHANGES_REQUESTED** [review]

File: drivers/nvme/host/pci.c [hunk 3]
```diff
@@ -4322,9 +4097,10 @@ static void nvme_reset_prepare(struct pci_dev *pdev)
 
 	/*
 	 * We don't need to check the return value from waiting for the reset
-	 * state as pci_dev device lock is held, making it impossible to race
-	 * with ->remove().
+	 * Fail any queued-but-not-submitted requests before disable
 	 */
+	nvme_qos_fail_all_queued_requests(dev);
+#endif
```
[the remark this answers is not in the document]
Comment (TSrirama2026) [reply drivers/nvme/host/pci.c]: I did, thanks for the catch

**Comment by TSrirama2026** [comment]
- Fails queued‑but‑not‑submitted QoS requests during reset/teardown using NVME_SC_HOST_ABORTED_CMD and NVME_REQ_CANCELLED, this matches the existing NVMe cancel semantics

- Draining QoS list before queue teardown so no list members outlive their queue structures using nvme_qos_fail_queued_results()

- Adds WARN_ON() checks in nvme_free_queue() (under CONFIG_NVME_QOS) to assert QoS lists are empty before freeing queue memory

- Quiesces the admin queue before completing QoS‑queued admin requests, and avoids redundant quiesce calls, to keep ordering and locking sane (Boss suggestion)

- All new behavior is under #ifdef CONFIG_NVME_QOS, so configurations without QoS see identical codegen and behavior

File: drivers/nvme/host/pci.c [hunk 4]
```diff
@@ -2363,8 +2412,20 @@ static void nvme_free_queues(struct nvme_dev *dev, int lowest)
...
+		 * yet, so they won't be handled by nvme_cancel_request().  Fail
+		 * them explicitly before freeing queue memory.
+		 */
+		if (nvmeq->sq_cmds)
+			nvme_qos_fail_queued_requests(nvmeq);
+#endif
+
 		dev->ctrl.queue_count--;
-		nvme_free_queue(&dev->queues[i]);
+		nvme_free_queue(nvmeq);
```
Comment (phannawich) [inline drivers/nvme/host/pci.c]: This change is outside of #ifdef CONFIG_NVME_QOS

**Review by phannawich — CHANGES_REQUESTED** [review]
I am going to be honest, I think you should consider rewrite the whole thing.

calling `blk_mq_complete_request(req)` in a while loop force the CPU to execute block layer completion for every request (or at least most of the request).

So at this point you could either 1. change the `request` to `nvme_iod` to fix the crash problem and edit codes that is outside Kconfig or 2. consider if the performance will drop due to the reason above and prevent it in the first place.

What I suggest you do:
1. Upgrade the `nvme_qos_purge_queue_locked` to also handle the `nvme_iod` not just `request`
2. Drop `nvme_qos_fail_all_queued_requests()` entirely because `nvme_dev_disable` already does the same thing by calling `nvme_cancel_tagset()`. This mean reverting the change inside `nvme_reset_work()` and `nvme_reset_prepare()`
3. Call the upgraded `nvme_qos_purge_queue_locked` function inside `nvme_suspend_queue` and `nvme_free_queues` (don't forget to unlink before freeing memory)

**Comment by phannawich** [comment]
I was going to take over issues #71 and I found out that applying my approach here should also solve the issues #71 and #93 at the same time.

**Review by BrandonPacewic — COMMENTED** [review]
I agree with @phannawich's suggestions. Here is the list of things I would want to see changed:

- [x] 1. Replace `nvme_qos_fail_queued_requests()` and `nvme_qos_fail_all_queued_requests()` with correct purge helpers.   
  - Both functions are broken and should be removed. They iterate the QoS lists using `struct request *` with the `queuelist` field, but the lists are actually threaded through `struct nvme_iod` via `qos_node`.
  - Replace them with two new functions:
    - `nvme_qos_purge_queue_locked(nvmeq)`: iterates the QoS lists using the correct `struct nvme_iod *iod` via `qos_node`, calling `list_del_init(&iod->qos_node)` on each entry. It only unlinks entries and does not complete them.
    - `nvme_qos_purge_queue(nvmeq)`: a thin wrapper around the above that acquires `sq_lock` using `spin_lock_irqsave()` before delegating to the locked variant.
- [x] 2. Restore the original structure of `nvme_suspend_queue()` and update the QoS call inside the guard
  - The `online_queues--` decrement was moved to after the quiesce call, which is a behavioural change that falls outside the `#ifdef CONFIG_NVME_QOS` guard. It must be restored to its original position before the quiesce. The #ifdef CONFIG_NVME_QOS block itself should remain in place, updated to call `nvme_qos_purge_queue(nvmeq)`.
- [x] 3. Fix the `#ifdef` scope in `nvme_free_queues()`
  - A `struct nvme_queue *nvmeq` declaration was introduced outside the `#ifdef CONFIG_NVME_QOS` block, and the `nvme_free_queue()` call was changed from `&dev->queues[i]` to `nvmeq`, both modifications leak outside the guard. The `nvmeq` declaration should be moved inside the `#ifdef` block, and the free call should be reverted to `nvme_free_queue(&dev->queues[i])`. The QoS-specific purge call within the guard should use `nvme_qos_purge_queue(nvmeq)`.
- [x] 4. Revert the `#ifdef` split in `nvme_reset_work()`
  - The straightforward `if (dev->ctrl.ctrl_config & NVME_CC_ENABLE) nvme_dev_disable(dev, false);` check was expanded into something that called `nvme_qos_fail_all_queued_requests()` before the disable. This is unnecessary:
    - `nvme_dev_disable()` already calls `nvme_suspend_queue()` for every queue, which handles QoS list cleanup under its own guard. This should be reverted.
- [x] 5. Remove the added QoS block from `nvme_reset_prepare()` entirely
   - The `#ifdef CONFIG_NVME_QOS` block calling `nvme_qos_fail_all_queued_requests()` is redundant, same reason stated above. The block should be removed entirely, leaving the function identical to its state on master.

I believe this will close all 3 issues #49, #71, and #93. Please let me know if I can help with anything at all.

**Review by phannawich — APPROVED** [review]
LGTM

**Review by BrandonPacewic — APPROVED** [review]
lgtm
